### ISSUE TITLE
How to use this input text field

### ISSUE THREAD

**Issue by shanks25** [nikku/jquery-tagit#6]
Hey, Great plugin, Can you please guide how to use this with the Html input text field, I want to pass the input array to my backend.

Thanks

**Comment by nikku** [comment]
The selected values are transmitted with the surrounding form via [hidden inputs](https://github.com/nikku/jquery-tagit/blob/master/lib/jquery.tagit.js#L25).

If you want to submit contents dynamically, you may check the forms `tag` values.
